name: Build and Email

on:
  push:
    branches:
      - main

jobs:
  email:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Read Release Notes
        id: read-release
        run: |
          RELEASE_NOTES=$(cat release-points.txt)
          echo "Release Notes: $RELEASE_NOTES"
          echo "::set-output name=release-points::$RELEASE_NOTES"

      - name: Send email
        uses: dawidd6/action-send-mail@v3.10.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          subject: 'Build Complete - NinjazTask'
          to: 'esraaahmed96h@gmail.com'
          from: 'hazem.emad.eprahim@gmail.com'
          body: |
            The build is complete!

            Release Information:
            ${{ steps.read-release.outputs.release-points }}

          attachments: |
            android/app/build/outputs/bundle/release/app-release.aab
            android/app/build/outputs/apk/release/app-release.apk
